### ISSUE TITLE
Cache pip when installing python

### ISSUE THREAD

**Issue by ryanhiebert** [getsentry/action-setup-venv#7]
The venv caching is great, but we can still use `cache: pip` in `actions/setup-python` to install the dependencies faster when they do change. If this needs to be able to be turned off, perhaps this can be done with an input that gets passed through to `actions/setup-python`. I'm happy to open a PR if this sounds like a good idea.

**Comment by asottile-sentry** [comment]
caching pip would make this slower for no benefit -- the virtualenv *itself* contains the dependencies and is the valuable bit to cache -- an additional cache with a copy of the dependencies wouldn't help and would immediately be invalidated just the same

**Comment by ryanhiebert** [comment]
I don't care what you do here, I've ended up vendoring a more customized version of what you have here.

But in my tests I've found that installations of new lockfiles with a large degree of overlap (such as when you upgrade the version of one of your dependencies, but most remain the same) does go appreciably faster with a pip cache, because for many packages even a not-quite-right cache will still have the version that we're trying to install, but this will (rightly) only use an _exact_ cache for the virtualenv.

**Comment by asottile-sentry** [comment]
that's not what the code for `actions/setup-python` indicates: https://github.com/actions/setup-python/blob/82c7e631bb3cdc910f68e0081d67478d79c6982d/src/cache-distributions/pip-cache.ts#L63

if the contents of your `**/requirements.txt` change it will invalidate the pip cache

**Comment by asottile-sentry** [comment]
fwiw the code as it is currently released is unlicensed meaning it should default to proprietary -- so you may not want to vendor until we've properly licensed it

**Comment by ryanhiebert** [comment]
Thanks for that warning on licensing.

In the section of the code that you link, note that the `primaryKey` includes the `hash`, but the `restoreKey` does not. This allows the cache loading to work with caches that aren't a perfect match, in order to speed up installation for different installation files as well.

**Comment by asottile-sentry** [comment]
sure -- but it's going to be downloaded always and used never

meaning in your ideal case you're downloading 2x what you need and in your rare case you're not improving much

**Comment by ryanhiebert** [comment]
Its always going to be downloaded, and used much less frequently, that's a great point that I had not caught. If we wanted to do this we could emulate what the `setup-python` pip cache is doing rather than using it built-in, which would allow us to skip the caching step if we found the virtualenv.

**Comment by ryanhiebert** [comment]
But anyway, feel free to not care about it, and thank you for discussing it with me enough to help me understand better.
